# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Pull
      run: git pull

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: gradle build

    - name: Test
      run: gradle test --info

    - name: Jacoco Test
      run : gradlew -i test jacocoTestReport

    - name: Jacoco Test Report
      run: gradle jacocoTestReport

    - name: ValidateSonar
      run: docker-compose up -d &
        sleep 50 &&
        ./gradlew sonarqube -Dsonar.host.url=http://localhost:9000 &&
        docker-compose down

    - name: Validate
      run: gradle sonarqube -Dsonar.host.url=http://localhost:9000

    - name: Deploy
      uses: AkhileshNS/heroku-deploy@v3.6.8
      with:
        heroku_api_key: "a0eed79f-6b9a-4530-81a0-6af9390c6a49"
        heroku_app_name: "spring-petclinic-tom"
        heroku_email: "tfernandez@est.frba.utn.edu.ar"
